- readme.md
- Point git clone url to NOAA-OWP instead of fork
> fix git clone github url

- src/python_routing_v02/compute_nhd_routing_SingleSeg.py
This change addresses two issues:
1. Closes an opened file handle that wasn't closed otherwise. This automatically flushes the file.
2. Removes a costly fsync on every write.
On my machine this results in the default test case runtime dropping to from 6.8s to 0.2s.
Ping: @jameshalgren
> Close file after writing

- src/python_framework/networkbuilder.py
- src/python_framework/nhd_network_utilities.py
To assist with determining points of connection between waterbodies and associated downstream segments/reaches/networks, this function adds a set designating the segments that are downstream of waterbodies -- i.e., the upstream-most segments of networks below a water body. 
The main work of this function occurs in networkbuilder.py in the function `get_waterbody_segments`. The various sets generated by the get_waterbody_segments are returned as part of the tuple handled by the `get_nhd_connections`  in nhd_network_utilities.py. 
The result of this change is observed by directly executing networkbuilder.py:
```
python networkbuilder.py
``` 
... or by calling the function with one of the example networks in the network traversal tool, setting the debuglevel to 3 to get a full printout of …
> Add print waterbody downstreams

- src/python_framework_v02/nhd_network_utilities_v02.py
See issue #133 
>Needed to change this because version has been updated online. nw,.v2.0.2 no longer exists. Without this change, any existing code that automatically downloads the NHD dataset will not work.
Originally posted by @awlostowski-noaa in #88 (comment)
>  Change 2.0.2 --> 2.0.3 in v02 network utilities

- src/python_routing_v01/compute_nhd_routing_SingleSeg.py
Correcting the CSV and NC write capabilities, which were broken with #137 
The input handler was passing `{"csv_output_folder":None}` and should instead have been passing simply `None`
This was corrected by better logic in the input handler as well as a slight change to the arg parser to provide a default value if the `-ocsv` or `-onc` flags are provided with no arguments. (The argument they accept is a custom path; the default paths are `../../test/output/csv` and `../../test/output/nc` )
> Bugfix csv nc write

- src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py
Short-time-step argument was not included in the script calls to the compute_network function. 
This PR corrects the omission.
NOTE: Initial testing shows that the output is consistent with our Pocono_TEST2 standard test. The computational error will be corrected in a separate PR.
> Include short time step arg in compute_network call

- src/fortran_routing/mc_pylink_v00/MC_singleSeg_singleTS/makefile
- src/python_framework_v02/setup.py
- src/python_framework_v02/troute/nhd_io.py
- src/python_framework_v02/troute/nhd_network.py
- src/python_framework_v02/troute/nhd_network_utilities_v02.py
- src/python_routing_v02/build_tests.py
- src/python_routing_v02/compiler.sh
- src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py
- src/python_routing_v02/fast_reach/mc_reach.pyx
- src/python_routing_v02/setup.py
- test/input/json/CustomInput.json
- test/input/yaml/CustomInput.yaml
__TL; DR:__ Major Update -- basically all features of T-Route V 2.0 except for Reservoirs, Data Assimilation, and Output control. Test features of this PR with the following commands: 
- micro test of all features: `python compute_nhd_routing_SingleSeg_v02.py -f ../../test/input/yaml/CustomInput.yaml`; 
- a bigger dataset with no WRF-Hydro input: `python compute_nhd_routing_SingleSeg_v02.py -n Mainstems_CONUS -tv --nts 288 --parallel by-subnetwork-jit-clustered --subnet-size 150 --debuglevel 1`
- __New Issue/PR:__ Add Falls Lake Florence Event (requires not-yet-available input datasets + input file) 
- __New Issue/PR:__ Add CONUS Benchmark Test (currently only works on Cheyenne; requires input file)
<br>__Important__ This PR Replaces #166 and #175 and is the follow-on for #185
This PR …
> Subnetwork final + Model Version 2.0 alpha2

- src/python_framework_v02/troute/network/reach.pxd
- src/python_framework_v02/troute/network/reach.pyx
- src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py
- src/python_routing_v02/fast_reach/mc_reach.pyx
Will add to this documentation in the near future, just wanted to get this up.  Ping me if I forget to fill it in.
-
-
Below are profiles of the compute functions taken from MAINSTEMS_CONUS_FULL_RES_v20.  Note that one of the biggest differences is in some calls to `numpy.array` in `compute_network_structured` that I think could be worked around, but the numpy arrays were used for the ease of indexing by a list of indicies outside the main timestep iterations.
Profiling of `compute_network`:
```
[2729077 rows x 432 columns]
414083126 function calls in 485.252 seconds
Ordered by: internal time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
14351  395.304    0.028  484.189    0.034 mc_reach.pyx:147(compute_network)
78051906   35.625    0.000   72.515    0.000 …
```
> Structured network compute

- src/python_routing_v02/fast_reach/mc_reach.pyx
Minor changes bringing efficiency improvements to the process of masking out upstream dependencies in the flowveldepth array, when running "by-subnetwork-jit-clustered" simulation
1. Simplify pre-filling of flowveldepth with upstream dependencies
```python
cdef np.ndarray fill_index_mask = np.ones_like(data_idx, dtype=bool)
cdef Py_ssize_t fill_index
cdef long upstream_tw_id
cdef dict tmp
cdef int idx
cdef float val
for upstream_tw_id in upstream_results:
tmp = upstream_results[upstream_tw_id]
fill_index = tmp["position_index"]
fill_index_mask[fill_index] = False
for idx, val in enumerate(tmp["results"]):
flowveldepth[fill_index][idx] = val
```
2. Simplify mask application in return statements
```python
return np.asarray(data_idx, dtype=np.intp)[fill_index_mask], np.asarray(flowveldepth, …
```
> Masking updates in mc_reach

- src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py
run_parameters["subnetwork_target_size "] = args.subnetwork_target_size  to run_parameters["subnetwork_target_size"] = args.subnetwork_target_size
> removed space that breaks arg call

- src/python_framework_v02/troute/nhd_io.py
- src/python_framework_v02/troute/nhd_network_augment.py
- src/python_framework_v02/troute/nhd_network_utilities_v02.py
- src/python_routing_v02/build_tests.py
- test/input/yaml/CustomInput.yaml
Moving all path manipulation (os.path and glob.glob) to pathlib.  Subsumes all content in #221 
Testcases:
> Move Path manipulation to pathlib

- src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py
Bug fix to recent waterbody PR. wbodies was being passed to the network splitting function, which resulted in improper partitioning -- waterbodies need to be isolated to their own networks, which now happens properly with this fix.
All simple tests pass:
We were handing over the wrong set: 
wbodies is the dict of segments that are waterbodies, for instance: 
```
{4186223: 4184997,
4186287: 4185089,
4186297: 4185089,
4186305: 4185089,
4186307: 4185089,
4186309: 4185089,
4186331: 4185105,
4186333: 4185105,
4186345: 4185105,
4186347: 4185105,
4186355: 4185105,
4186357: 4185105,
4186359: 4185105,
4186361: 4185105,
4186363: 4185105,
4186371: 4185105,
4186379: 4185105}
```
Those were never found by the splitting algorithm because they had been removed from the network.
vs.
the index of the new …
> Fix waterbody splitting

- src/fortran_routing/Reservoir_Binding/Reservoirs/makefile
- src/fortran_routing/mc_pylink_v00/MC_singleSeg_singleTS/makefile
- src/python_routing_v02/compiler.sh
This resolves the issues with missing symbols on my machine as well as
the troubles with the netcdf library.
The root of the issue was the hardcoding of gfortran in the makefiles. The netcdf library issues were resolved by querying netcdf library for the include paths and linking options.
tag: @hellkite500 @jameshalgren
> Fix compile errors.

- src/python_routing_v02/fast_reach/mc_reach.pyx
change `flowveldepth[fill_index][idx] = val` to  `flowveldepth[fill_index, idx] = val`
#249 
Just made the tiny changed listed in the above comment.
> Use comma [i,j] index instead of [i][j]

- src/python_framework_v02/troute/nhd_io.py
- src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py
- test/input/yaml/CustomInput.yaml
New capability to write t-route simulated flow and depth data to WRF-Hydro restart files. The routine opens each WRF-Hydro restart file 
1. Construct a datetime array for the t-route simulation. This is needed to query t-route results against timestamps specified in WRF-Hydro Restart Files. 
2. Re-index the `flowveldepth` dataframe to match segment ID ordering in the Restart FIle
3. Open each WRF-Hydro restart file in a user-specified restart file directory with user specified file pattern filter
1. Extract restart timestamp by converting Restart_Time attribute to datetime64 datatype
2. Find the index of t-route datetime array that matches timestamp in Restart File. 
3. IF a matching timestamp is found, THEN  create Data Arrays of t-route flow and depth data for the matching timestamp, …
> Write t-route states to WRF-Hydro restart files

- src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py
This super brief pull request updates the csv handling slightly to allow more easily for and empty output field in the control yaml file, thus: 
``` yaml
output_parameters:{} 
```
or 
``` yaml
#output_parameters:
```
Passes the following tests without changes to prior behavior: 
```
#!/bin/bash -x
python compute_nhd_routing_SingleSeg_v02.py -f ../../test/input/yaml/CustomInput.yaml
python compute_nhd_routing_SingleSeg_v02.py -f ../../test/input/yaml/Croton_NY_levelpool.yaml
python compute_nhd_routing_SingleSeg_v02.py -f ../../test/input/yaml/Croton_NY_with_wb_dev.yaml
python compute_nhd_routing_SingleSeg_v02.py --test pocono1 -t -v --debuglevel 1
python compute_nhd_routing_SingleSeg_v02.py -t -n Mainstems_CONUS -v --debuglevel 1 --parallel by-network --nts 288 --cpu-pool 6
python …
```
> simplify handling of output flags

- src/fortran_routing/Reservoir_Binding/Reservoirs/makefile
- src/python_routing_v02/compiler.sh
- src/python_routing_v02/troute/routing/compute.py
- src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx
- test/input/yaml/Croton_NY_levelpool.yaml
This pull requests enables by-subnetwork parallelization of the compute_network_structured routing compute method. The basic idea of these changes is to write the flow, velocity, and depth to the flowveldepth array for the upstream neighboring segments of a particular sub-network.
> [UPDATED (again)] Enabling by-subnetwork parallel in `mc_reach.compute_network_structured`

- src/nwm_routing/src/nwm_routing/__main__.py
- src/python_routing_v02/troute/routing/compute.py
- src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx
- test/input/yaml/Florence_Benchmark_da.yaml
This pull requests suggest three contributions to the codebase:
The basic workflow of replacing flow simulations with gage observations is borrowed from the `mc_reach.compute_network` method and implemented in `mc_reach.compute_network_structured`. This is an important contribution because data assimilation is otherwise not possible in `mc_reach.compute_network_structured`. Moreover, `mc_reach.compute_network_structured` is the only compute scheme capable of handling reservoirs. This update gives us the capability to include both reservoirs and DA into a routing simulation. 
At this time, DA decay is not yet included and will be considered in a forthcoming PR.  
The scheme used to sub-sample WRF-Hydro qlateral data in `mc_reach.compute_network_structured` was incorrect. This has been …
> DA compatibility with structured compute method 

- src/python_routing_v02/troute/routing/diffusive_utils.py
This micro PR converts to a new usage: we create an instance of IVDataService and call the get method of that instance. 
The get method previously was a classmethod, but in the new version it is not. This change was to support better caching and other optimizations. The good news is, the new syntax is backward compatible to the previous version of the nwis client so no change is needed to any existing environments with this update, but now we can support any newer environments. Please see #337 for additional information.
**Note:** The dependency on NWIS client access within `diffusive_utils.py` is probably non-optimal (placement within `nhd_io.py`, for instance, seems more appropriate). This PR is focusing on an issue that prevents migrating to newer environments, needed for asynchronous …
> Update IVDataService call

- src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx
This request adds reservoir initial outflow writing to the `flowveldepth_nd` array in `mc_reach.compute_network_structured`. Previously, reservoir initial outflows were not being written to `flowveldepth_nd`, was causing incorrect flow simulations immediately downstream of reservoirs. Recall - upstream flow conditions at current and previous timesteps are used as boundary conditions for segment-level MC simulations. As it turns out, upstream boundary flows below reservoirs were equal to zero for the first timestep of a simulation. This caused t-route flows to be lower than WRF hydro flows. 
Notice the first timesteps of the parity check print out. T-route flows are noticeably lower than WRF hydro.
```
flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
2011-08-26 01:00:00 …
```
> correct handling of reservoir initial flows

- src/nwm_routing/src/nwm_routing/__main__.py
- src/nwm_routing/src/nwm_routing/preprocess.py
- src/python_framework_v02/troute/nhd_network.py
- src/python_framework_v02/troute/nhd_network_utilities_v02.py
- src/python_framework_v02/troute/test_nhd_network.py
- src/python_routing_v02/troute/routing/compute.py
Somewhere, way back, we had some sort of catch for a case where a set of masked segments that were part of a larger network would generate a valid connections set by setting the off-network terminal nodes to negative values. These 'to' or 'downstream' segment ids exist in the larger network, but when masked, are not part of the computation domain. Somewhere along the way, we lost that catch, but since all of our test cases had been boiled down to situations where the terminal codes are all 0, apparently. Or we have been just lucking-out. 
Either way, this introduces a more clear usage of the "terminal_code" and modifies the principal call in the code to this function to use the code and any non-standard internal codes in the call to the function `extract_connections`. 
~~The PR is frozen …
> Interior terminal nodes

- src/fortran_routing/Reservoir_Binding/Reservoirs/RFC_Forecasts/module_rfc_forecasts.F
- src/fortran_routing/Reservoir_Binding/Reservoirs/RFC_Forecasts/module_rfc_forecasts_properties.F
I added capability for Reservoir RFC module to assimilate Alaska glacier dam release forecasts. This does not affect the regular functionality of RFC-type reservoirs.
Needed for NWM V3.0
src/fortran_routing/Reservoir_Binding/Reservoirs/RFC_Forecasts/module_rfc_forecasts.F 
src/fortran_routing/Reservoir_Binding/Reservoirs/RFC_Forecasts/module_rfc_forecasts_properties.F
1. Passes existing Croton LP and RFC tests.
> Reservoir RFC module updates for Alaska glacier release forecasts

- src/nwm_routing/src/nwm_routing/__main__.py
- src/nwm_routing/src/nwm_routing/output.py
- src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx
Bugfix to return capability for returning courant number for simulations using the V02-caching compute kernel. Per comments in issue #362 the problem was that an additional index position was added to accomodate initial conditions in the main array but not in the courant array. This PR now makes the behavior for the courant array match the flowveldepth array. We could probably avoid this somehow, but this seems to work for now. 
This does not yet fix the broken test `python -m nwm_routing -V2  -f ../../test/input/yaml/Florence_Benchmark.yaml` because the yaml file refers to the `V02-structured` compute method, which does not yet handle the courant output properly.
> [WIP] Courant timestep bugfix

- src/python_routing_v02/troute/routing/compute.py
The timestamp in the qlateral files is sometimes a datetime object, sometimes a string. So, we had logic in each parallel execution mode that handled both cases. 
But if qlat_const is used to supply a constant qlateral, there is no date of any kind in the dataframe. This fixes the issues where that lack of a date value threw an error and also encapsulates the logic into a function (`_format_qlat_start_time`) to reduce the duplication.
~~*Note: The commits suggested in #380 are contained in this PR. If needed  (i.e., if that PR is determined to be un-needed), the single relevant commit for this PR, [027f5a548b6d6a96eade154494a0540ecb37ef3b](https://github.com/NOAA-OWP/t-route/pull/388/commits/027f5a548b6d6a96eade154494a0540ecb37ef3b) could be rebased on something more useful.~~
The …
> Timestamp bugfix

- src/fortran_routing/mc_pylink_v00/MC_singleSeg_singleTS/makefile
- src/nwm_routing/src/nwm_routing/__main__.py
- src/python_routing_v02/troute/routing/compute.py
- src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx
- src/python_routing_v02/troute/routing/fast_reach/simple_da.pxd
- src/python_routing_v02/troute/routing/fast_reach/simple_da.pyx
pr #358 left a few items incomplete on the `V02-caching` and `V02-structured-obj` computation modes. Those are not target operational modes so the PR was merged in spite of that. 
This PR fixes those items (using the loop-less da procedure; using `_i` for temporary indexes) and also updates the `V02-structured` DA algorithm with a minor but important update to the timestep indexing. 
The output parity is now slightly better:
> Da update for caching structured obj

- src/python_routing_v02/build_tests.py
The relative difference value is useful in determining significance of flow errors.
> add relative difference as a statistic in parity output

- src/python_routing_v02/troute/routing/compute.py
by-subnetwork parallel simulations were breaking with the Florence_Benchmark_da simulations. After some digging, I found that there was a gage link in the offnetwork upstreams list. This caused `da_positions_list_byreach` to be one item shorter than `da_positions_list_byseg`, which blew up the simulation with an indexing error in `mc_reach.compute_network_structured`. 
To fix this, I pass the `offnetwork_upstreams` list to `_prep_da_dataframes` (default  `offnetwork_upstreams = []`), in addition to `param_df_sub.index`. Then I create a new list called, `subnet_segs`, which contains ONLY the segments in the subnetwork. This list is searched for gage segments. The `param_df_sub_idx` list is handled with `get_indexer()` such that the `param_df_sub` array is correctly indexed in downstream …
> bugfix: gages in offnetwork upstream list blows up by-subnetwork parallel simulations

- src/nwm_routing/src/nwm_routing/__main__.py
- src/python_framework_v02/troute/nhd_io.py
- src/python_framework_v02/troute/nhd_network_utilities_v02.py
The interpolation scheme used upon read for the USGS time slice files controls a number of aspects of the ultimate result of the data assimilation scheme. This PR will accomplish the following: 
* Revise TimeSlice file loading to eliminate duplicating observations across unique times in the file. 
* Interpolate observations from given time intervals to a 5-minute frequency with NaN threshold (interpolation does extend through NaN gaps of a specified length). 
* Trim the temporal extent of usgs_df such that the first column is temporally aligned with restart time.
* Get quality flag data from TimeSlice files, organize data into a DataFrame with same dimensions and indexing as `usgs_df`, pass this out to `__main__.py`
* Use quality flag data to screen poor observations from the DA workflow …
> Update USGS TimeSlice interpolation scheme and include quality control flags

- src/nwm_routing/src/nwm_routing/__main__.py
- src/python_framework_v02/troute/nhd_io.py
- test/input/yaml/CustomInput.yaml
- test/output/.gitignore
The WRF-Hydro-style output currently relies on an existing output folder, which is scanned, and then a duplicate set of output files are generated (CHRTOUT or HYDRO_RST) with the t-route streamflow values populating the results. 
This PR allows for that write to occur in a different directory than the source files which are scanned.
> Allow flexible output folder for WRF-Hydro output files

- src/nwm_routing/src/nwm_routing/__main__.py
- src/nwm_routing/src/nwm_routing/preprocess.py
- src/python_framework_v02/troute/network/reservoirs/hybrid/hybrid_structs.c
- src/python_framework_v02/troute/network/reservoirs/levelpool/levelpool_structs.c
- src/python_framework_v02/troute/network/reservoirs/rfc/rfc_structs.c
Change initial reservoir cold start water elevation to -1e9 and check to less than -900000000 to allow negative water elevations at warm start.
-
-
-
1.
-
-
> Reservoir Cold Start Water Elevation Check

- src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx
This PR corrects the indexing of waterbodies in `mc_reach.compute_network_structured`. There was an assumption being made that the rows in the `wbody_parameters` array were ordered in-line with the reservoir reaches in `reaches_wTypes` tuples. This assumption is manifested in the `wbody_index` variable, which is initialized at 0 and increases by 1 after each time the `reach_objects` variable is appended for a waterbody. This was resulting in reservoirs being incorrectly initialized and parameterized, causing obvious downstream issues. 
The `wbody_index` variable is now defined by a binary search used to identify the index location of reservoir reach ID in the `lake_numbers_col` list. This fix ensures that we are taking the parameters and initial conditions from the correct row positions …
> correct waterbody indexing in mc_reach with binary search

- src/python_framework_v02/troute/nhd_io.py
A breakpoint was inadvertently committed and merged.
> bugfix: remove committed breakpoint

- src/nwm_routing/src/nwm_routing/__main__.py
- src/nwm_routing/src/nwm_routing/preprocess.py
- src/python_framework_v02/troute/nhd_io.py
- src/python_framework_v02/troute/nhd_network_utilities_v02.py
- src/python_routing_v02/build_tests.py
- src/python_routing_v02/troute/routing/compute.py
- src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx
- src/python_routing_v02/troute/routing/fast_reach/simple_da.pyx
- test/input/yaml/Florence_Benchmark_da.yaml
This PR implements the full input interface functionality of the NWM routing module simulation elements with
Follow-on PRs will address the following
***Note***: The V3 designation is only loosely tied to the NWM v3.0 version number for which this capability is targeted; Semantically, this essentially represents a new version of the model, as the input version is now completely different and significant new functionality is introduced. 
* Update front-end interface
* Split LastObs and TimeSlice preprocessing to recognize relation to initial states vs. continual forcing
* Add additional return from compute kernel with LastObs updated through simulated series
* Use returned lastobs with other warm states
* Adjust logic for TimeSlice read to accommodate repeated calls in consecutive loops
* …
> Long term looping all elements

- src/python_framework_v02/troute/nhd_io.py
- src/python_framework_v02/troute/nhd_network_utilities_v02.py
Gage IDs in the NWM 2.1 dataset include gages in Canada with non-numeric IDs. Based on gages from the USGS numbering system, only numeric gage IDs were being accepted and the alphanumeric Canadian gages were being removed. Those gages should now be properly handled and retained.
> Handle nonnumeric gage ids

- src/fortran_routing/diffusive_v02frwk/diffusive.f90
- src/fortran_routing/diffusive_v02frwk/diffusive_cnt/diffusive_cnt.f90
- src/python_framework_v02/troute/nhd_network.py
- src/python_routing_v02/troute/routing/compute.py
- src/python_routing_v02/troute/routing/diffusive_utils.py
- src/python_routing_v02/troute/routing/fast_reach/diffusive.pyx
- src/python_routing_v02/troute/routing/fast_reach/diffusive_cnt.pyx
This PR adds the capability to do data assimilation (DA) with the diffusive wave model. At gage locations, simulated flows are either replaced with interpolated USGS observations, or nudged by some amount (in the event that observations are missing). Replaced/nudged flows at gage locations are then routed downstream. The DA scheme does not propagate any gage information upstream. Instead gage information (flow) is only passed in the downstream direction. The approach used for observation interpolation, DA substitution, and DA decay is exactly the same as is used with Muskingum-Cunge. 
- DA with the diffusive wave model is facilitated by subnetwork creation. The spatial unit of analysis for the diffusive wave Fortran kernel is a stand-alone stream network, as opposed to a single segment in …
> Data Assimilation (DA) for the diffusive wave model(s)

- src/nwm_routing/src/nwm_routing/__main__.py
- src/python_framework_v02/troute/nhd_io.py
- src/python_framework_v02/troute/nhd_network_utilities_v02.py
This PR is built off of the fixes found in jameshalgren/long-term-looping-all.
This PR should address the feature requests in:
**https://github.com/NOAA-OWP/t-route/issues/433**
marked at:
- https://github.com/NOAA-OWP/t-route/blob/4ec74cc70d4f1ca407d20a6764b3f89facb43a96/src/python_framework_v02/troute/nhd_io.py#L757
- https://github.com/NOAA-OWP/t-route/blob/4ec74cc70d4f1ca407d20a6764b3f89facb43a96/src/python_framework_v02/troute/nhd_io.py#L652
- https://github.com/NOAA-OWP/t-route/blob/4ec74cc70d4f1ca407d20a6764b3f89facb43a96/src/python_framework_v02/troute/nhd_io.py#L776
The frequency needed to be calculated using the run_parameters['dt']. I made a few changes to pass run_parameters through the necessary functions to get it there. Additionally, a slight modification to …
> allow different intervals for data assimilation

- src/fortran_routing/diffusive_v02frwk/diffusive_cnt/diffusive_cnt.f90
- test/input/yaml/Florence_Benchmark_diff.yaml
Four lines of code made to subroutine mesh_diffusive_backward in diffusive_cnt.f90 enable the use of dtini (simulation time step) smaller than 600sec. Now, with dtini=300sec, CNT runs without instability.    Note that it is recommend to use saveinterval_cnt in diffusive_utils.py in the form of multiplier*dt, where multiplier close to 12.  Further test on the multiplier is on the way.
-
-
-
1. python3 -m nwm_routing -V2 -f ../../test/input/yaml/Florence_Benchmark_diff.yaml
-
-
> stability addition to CNT for smaller simulation time step

- src/nwm_routing/src/nwm_routing/__main__.py
This PR introduces asynchronous IO to the looped execution capability recently demonstrated in the t-route code (see #429). 
The idea behind the looping execution is that, with proper garbage collection, T-route can provide a solution of arbitrary length (because T-Route loads all variables for a particular loop in memory, the length and size are limited by system resources). But with the looping execution, the idea of asynchronous data loading is that after the first block of data has been loaded and the simulation started with that block, the reading of subsequent blocks can begin immediately. If the read and execution sequences are staggered on different process pools, the simulation can proceed without overwhelming the memory -- but also without waiting too much for the data to load …
> Allow forcing datasets to load asynchronously during model execution

- src/python_routing_v02/troute/routing/fast_reach/diffusive.pyx
- src/python_routing_v02/troute/routing/fast_reach/diffusive_cnt.pyx
In order to enable simulations through the looped V3 execution pathway, we need to pass LastObs data from cython to `compute.py`. Our first implementation of DA in `diffusive.pyx` and `diffusive_cnt.pyx` did not gather and return LastObs data, which caused the V3 execution pathway to fail.
> Update diffusive DA to enable V3 exec pathway

- src/python_framework_v02/troute/nhd_io.py
- src/python_framework_v02/troute/nhd_network_utilities_v02.py
Two bug fixes are addressed with this PR
1. Correctly time-indexed data are now written to CHRTOUT. Prior to the changes to `nhd_io.write_q_to_wrf_hydro`, the data being written to CHRTOUT files was time-lagged by 1-hour. This is the likely explanation for why NCAR has been observing very different flow results from WRF and t-route. 
2. Fixed how the `nts` variable in each loop set is calculated.
> bug fixes: CHRTOUT writing, run_set creation

- doc/v3_doc.yaml
- src/nwm_routing/src/nwm_routing/__main__.py
- src/nwm_routing/src/nwm_routing/preprocess.py
- src/python_framework_v02/troute/nhd_io.py
- src/python_framework_v02/troute/nhd_network_utilities_v02.py
This PR proposes several changes that facilitate running simulations with WCOSS operational (transient)outputs.
- WRF simulations on WCOSS does not write a `q_lateral` variable to `CHRTOUT` files. Therefore, a `q_lateral` variable is not available to t-route for channel forcings. As a work around, we are introducing the capability to calculate `q_lateral` as `qBucket + qSfcLatRunoff`. Here, `qBucket` is the flux to the stream channel from the groundwater bucket model and `qSfcLatRunoff` is the flux to the channel from overland flow runoff.
- Default parameter value for `qlat_file_value_col` changed to `q_lateral` in `preprocess.py`
- A new capability is added that allows simulations to continue if all of the TimeSlice files in a particular loop set are missing. Previously, simulations …
> Framework updates to facilitate testing with WCOSS operations output

- doc/v3_doc.yaml
- src/nwm_routing/src/nwm_routing/__main__.py
- src/nwm_routing/src/nwm_routing/input.py
- src/nwm_routing/src/nwm_routing/preprocess.py
- src/python_framework_v02/troute/nhd_io.py
Introducing a preprocessing capability, whereby users can build and save network graph data objects for future use. Likewise, users can read and use pre-constructed network graph data objects. These capabilities are intended to reduce computationsl time spent on network graph construction tasks during operational uses. 
Network graph data objects refer broadly to the variables returned by [`nwm_network_preprocess`](https://github.com/NOAA-OWP/t-route/blob/7128442d01f3cdd1e02ab2d169e6940d82736fb4/src/nwm_routing/src/nwm_routing/preprocess.py#L14-L144) , a set of python dictionary and Pandas DataFrame variables that contain network topology  and/or channel geometry data. These data objects are bespoke to a simulations spatial domain, but not the temporal domain. For example, all of the …
> Preprocess network graph data

- doc/v3_doc.yaml
- src/nwm_routing/src/nwm_routing/__main__.py
- src/nwm_routing/src/nwm_routing/output.py
- src/nwm_routing/src/nwm_routing/preprocess.py
- src/python_framework_v02/troute/nhd_io.py
- src/python_framework_v02/troute/nhd_network_utilities_v02.py
- src/python_routing_v02/troute/routing/compute.py
This pull request proposes an overhaul of the current workflows used to read forcings from CHRTOUT and write t-route results to CHRTOUT and HYDRO_RST files. I've developed new functions in `nhd_io` that no longer rely on xarray.open_mfdataset or xarray.save_mfdataset. Instead, reading and writing is done with the netCDF4 library. Additionally, calls to read and write data are placed in joblib Parallel loops.
The most important change in the results writing process is that new carbon copies of CHRTOUT and HYDRO_RST files are no longer created. Rather, new variables are simply appended to the same CHRTOUT and HYDRO_RST files used to force and start the t-route simulation.
Much more logging throughout the output process is included, here. 
- CHRTOUT and HYDRO_RST writing is done with netCDF4 …
> Expedite file reading and writing processes

- doc/v3_doc.yaml
- src/nwm_routing/src/nwm_routing/__main__.py
- src/nwm_routing/src/nwm_routing/output.py
- src/nwm_routing/src/nwm_routing/preprocess.py
- src/python_framework_v02/troute/nhd_io.py
This pull request proposes a light restart capability, whereby final channel and waterbody states are saved to disk as pickle files after each computational loop. In the event that a long term simulation crashes, these restart files can be used to warm start the simulation from a point in time closer to where the simulation failed than the starting initial condition. 
- Ensured that my development branch generates the same exact flow, velocity and depth results as the upstream master. In other words, writing-out restart files along the way has no bearing on the physics solution.
- Also ensured that a simulation on the development branch that is warm started from a lite restart file produces the same result as a simulation warm started at an earlier time with a HYDRO_RST file. 
- Ensured …
> Light restart

- doc/v3_doc.yaml
- src/nwm_routing/src/nwm_routing/output.py
- src/python_framework_v02/troute/nhd_io.py
This PR proposes new output routines for writing flow results at gage locations to "CHANOBS" files. These additions are motivated by NWM3.0 calibration needs. 
- new function: `nhd_io.write_chanobs`, which writes flow results from segments co-located with stream gages to netCDF. If the  user-specified netCDF file does not yet exist, one is created. If the user-specified file already exists, flow results are simply appended to it. 
- New output arguments in configuration .yaml file specifying the directory and name of the netCDF file that results are to be written to. 
- New conditional call to `nhd_io.write_chanobs` in  `output.nwm_output_generator` that is activated if chanobs output parameters exist in configuration file. 
- None
- None
1.  Ran a 5.9 year (`nts=622000`) calibration …
> Write flow at gage locations to netCDF (CHANOBS) file

- doc/v3_doc.yaml
- src/nwm_routing/src/nwm_routing/preprocess.py
Allows users to specify a starting datetime of the simulation in the configuration file. t-route will give priority to the user-specified starting datetime when setting the `t0` variable. In the event that this new input is not provided by the user, or is incorrectly entered (unrecognizable datetime string), then t-route defaults to the start time in the restart file. If no restart file is available, then t-route defaults to an arbitrary starting date. Logging info messages are thrown to notify users as to which starting datetime is used. 
There is a new parameter, `start_datetime`, in the configuration file, under `restart_parameters`.
> read start time from configuration file

- src/nwm_routing/src/nwm_routing/__main__.py
- src/nwm_routing/src/nwm_routing/output.py
- src/nwm_routing/src/nwm_routing/preprocess.py
- src/python_framework_v02/troute/nhd_network.py
This Pull Request changes the final index values of waterbody nodes in a simulation domain. Specifically, I am proposing to rename the index values on waterbody nodes from lake ids to the segment link id of the waterbody outlet. Without this change, t-route returns NaN values of outflow and depth for waterbody outlet segments in CHRTOUT files, which is inconsistent with required output writing protocol. 
- The construction of a new `link_lake` dictionary that relates waterbody lake ids to the corresponding link id of the waterbody outlet segment. This dictionary is created in `nhd_network.replace_waterbodies_connections` and passed throughout framework code as an eventual input argument to `nwm_output_generator`. This dictionary is created by first finding upstream connections of the …
> Write waterbody results to waterbody outlet segments

- src/nwm_routing/src/nwm_routing/output.py
- src/python_framework_v02/troute/nhd_network.py
Turns out that the solutions in #516 did not scale nicely to CONUS. This is because pandas `rename()` is slow on very large dataframes, such as the `flowveldepth` dataframe produced for CONUS results. Here, I am rewriting the process of renaming `flowveldepth` index values using numpy, which turns out to be many orders of magnitude faster.
> speeding up the renaming of flowveldepth indices: lakeid <> segid

- src/python_routing_v02/troute/routing/fast_reach/simple_da.pyx
Further testing of t-routes DA scheme at CONUS scale revealed some issues that were not observed at smaller development scales. In particular, there were negative and -Inf values appearing at gage locations. As it turns out, the DA-decay method had but in it. Specifically, the DA weight value is: `da_weight = exp(time_since_lastobs/ decay_coeff)`, where `time_since_lastobs` is the number of minutes since the last quality observation was taken at the gage. Per this, equation `time_since_lastobs` should not be a negative value, but the existing code was simulating as such. 
Elaborating a bit more with some context. The DA weight is weight that a simulated value is given relative to the last observation. When the last observation occurred very recently, the weight on the simulated value …
> Streamflow DA bug fix (negative values)

- src/troute-network/troute/nhd_io.py
- src/troute-network/troute/nhd_network_utilities_v02.py
- src/troute-nwm/src/nwm_routing/output.py
This Pull Request proposes a bug fix and a change.
- A bug was found in PR #520, whereby waterbody outflow (and water elevation) values were being written to the wrong waterbodies. Here, we fix the indexing such that we are writing results to the correct waterbody outlet segments.
- We explicitly change the preferred source of lateral inflow data in CHRTOUT files. Instead of preferring to get lateral inflow data from the `q_lateral` variable, we no prefer to get lateral inflow from the sum of `qBucket` and `qScfLatRunff` terms. The reason for this change is to conform with WRF-Hydro's routing model.
> lake<>segment indexing fix and qlateral preference change

- .gitignore
- src/troute-nwm/src/nwm_routing/preprocess.py
hotfix to `preprocessing.py` to fix missing gage segment set argument in organize_independent_networks.
- adding .ipynb_checkpoints/ to .gitignore to reduce unwanted commits
- adding empty set arg to organize_independent_networks when building build diffusive domain data
- no errors when running `test_AnA.yaml` using both True and False for `run_hybrid_domain`
> hotfix for diffusive wave independent networks

- src/troute-network/troute/nhd_io.py
- src/troute-nwm/src/nwm_routing/__main__.py
- src/troute-nwm/src/nwm_routing/preprocess.py
- src/troute-routing/troute/routing/compute.py
The purpose of this Pull Request is to speed up workflows related to the handling of TimeSlice data for streamflow and reservoir data assimilation. The changes here were initially prompted by the sluggish performance of the existing method for nan-filling TimeSlice data by interpolation using pandas `DataFrame.interpolate()`, which fills interpolates through nan gaps on a row-by-row basis. At CONUS scale, with over 7k gages, interpolation can take ~3 - 4 seconds, and this happens at every loop iteration, which is cumulatively costly for long-term simulations. Here, I went ahead and parallelized the implementation of `DataFrame.interpolate()`, by farming-out small chunks of gages to separate CPUs so that we can simultaneously interpolate many gages at the same time. Overall, this change …
> Expedite time slice interpolation routine

- src/troute-routing/troute/routing/compute.py
A recent pull request disrupted the ability to run open loop simulations without any reservoirs. Here, we provide a fix for that disruption 
- revised logic in `compute._prep_reservoir_da_dataframes` that allows `waterbody_types_df_sub` to be empty.
> hotfix: reservoir DA data-prep logic

- src/troute-routing/troute/routing/diffusive_utils.py
This is a quick bug fix that allows the diffusive hybrid model to work with looped simulations (addressing #535). The diffusive wave input argument `traps_ar_g` is the reciprocal of the trapezoidal channel side slope. Previously, there was a line of code that was taking the reciprocal of channel side slope in `diffusive_utils`:
```python
param_df.loc[:,'cs'] = 1/param_df.loc[:,'cs']
```
The issue with the line of code above is that it alters the entire input dataframe column and that alteration is retained for the next loop. So on the second loop iteration, we end up taking the reciprocal of the reciprocal!  The problem was easily fixed by moving the reciprocal operation lower down and not performing it on the entire dataframe column.
> Bug fix allowing looped diffusive hybrid simulations

- src/troute-network/troute/network/reservoirs/levelpool/levelpool.pyx
- src/troute-network/troute/nhd_io.py
This pull request enables levelpool reservoir simulations with int64 type waterbody IDs. There are int64 waterbody IDs in the Alaska domain, where were causing the model to fail because the waterbody ID was expected to be int32 type. This fix will facilitate oCONUS calibration simulations.
> Alaska reservoir fix

- src/troute-nwm/src/nwm_routing/__main__.py
- src/troute-nwm/src/nwm_routing/preprocess.py
- src/troute-routing/troute/routing/compute.py
- src/troute-routing/troute/routing/fast_reach/mc_reach.pyx
There are several state parameters that need to passed over between reservoir DA simulation loops:
- **update time** - model time (seconds since simulation start) at which new observations are sought for assimilation
- **previously persisted outflow** - value of the persisted outflow from the previous timestep
- **persistence update time** - model time (seconds since simulation start) at which the persisted reservoir outflow is reconsidered.
- **persistence index** - the number of elapsed persistence update intervals
These parameters are updated for each reservoir at each timestep. When we run a simulation looped over temporal chunks, the parameter information must be passed from one loop to the next. Else, the parameters will reset to default values. If the parameter information is not …
> Simulation looping with hybrid reservoir data assimilation

- src/troute-nwm/src/nwm_routing/preprocess.py
- test/LowerColorado_TX/test_AnA.yaml
This pull request proposes slight changes in `preprocess.py` that facilitate the use of the most recent natural cross section data product produced by GID (March 31, 2022). Additionally, changes are made to the Lower Colorado test case. Namely, additional parameters in the YAML configuration file that allow users to use natural cross section data and the natural cross section data file for the Lower Colorado diffusive domain. 
Note: In order to use natural cross section data, there must be cross section data available for every segment in the diffusive domain.
> Natural cross section integration (non-refactored)

- doc/v3_doc.yaml
- src/troute-network/troute/nhd_io.py
- src/troute-nwm/src/nwm_routing/__main__.py
- src/troute-nwm/src/nwm_routing/output.py
- src/troute-routing/troute/routing/compute.py
- src/troute-routing/troute/routing/fast_reach/mc_reach.pyx
- test/LowerColorado_TX/test_AnA.yaml
Added the capability to write LAKEOUT netcdf files containing inflow, outflow, and depth of waterbodies. One file is created per time step of the run.
- lakeout_output parameter to output parameters in yaml file (documentation also added to v3_doc.yaml)
- added lakeout directory in test directory where LAKEOUT netcdf files will be saved.
- write_waterbody_netcdf function to nhd_io.py file. This function writes one netcdf file per time step containing information for all waterbodies
- waterbodies_df and waterbody_types_df added as input parameters to nwm_output_generator function in __main__.py
- waterbodies_df and waterbody_types_df added as input parameters to nwm_output_generator function in output.py
- added wbdyo from lakeout_ouput parameter in nwm_output_generator function
- added …
> write waterbody results to LAKEOUT files

- src/kernel/muskingum/MCsingleSegStime_f2py_NOLOOP.f90
The v3.0 RouteLink file contains stream segments with zero-valued floodplain widths, which causes issues in the existing MC kernel - specifically NaN flow predictions. The same issues are also caused in the WRF Hydro MC kernel - addressed in this PR: https://github.com/NCAR/wrf_hydro_nwm_public/pull/599
The changes proposed here include some additional conditions on if statements that account for situations when the water height is greater than the trapezoidal channel bank full height and the floodplain width is zero. 
1. The newly changed MC kernel produces the same exact results as the old one. 
2. NCAR will conduct additional testing to make sure the changes work with the v3.0 RouteLink
> MC kernel updates for V3.0 RouteLink

- src/troute-nwm/src/nwm_routing/__main__.py
Code fails for situations when the `reservoir_types_df` is empty, which can occur if the user opts not to simulate waterbodies or there are no waterbodies in the domain, and there are more than one loops for a simulation. This is fixed by adding an if-statement in `__main__.py`, that avoids referencing `reservoir_types_df` columns if the dataframe is empty.
The new code (lines 542 - 562 in `__main__.py`) appear below. You can see that the outermost if-statement guards against referencing the `waterbody_types_df` dataframe if it is empty. 
``` python
if not waterbody_types_df.empty:
if 2 in waterbody_types_df['reservoir_type'].unique():
if reservoir_usgs_df.empty and len(reservoir_usgs_param_df.index) > 0:
reservoir_usgs_df = pd.DataFrame(
data    = np.nan, 
index   = …
```
> bug fix: empty reservoir_types_df causes failure when looping

- src/troute-nwm/src/nwm_routing/__main__.py
- src/troute-routing/troute/routing/compute.py
Changes made to only calculate subnetworks on first iteration of for loops. Subnetwork objects needed in compute.py are stored in a new list, subnetwork_list, which is passed to and returned from functions nwm_route and compute_nhd_routing_v02.
- New object, subnetwork_list, stores either two (for "by-subnetwork-jit-clustered") or three (for "by-subnetwork-jit") subnetwork objects.
- subnetwork_list is passed to and returned from two functions,  nwm_route and compute_nhd_routing_v02, as second item in list. The first item is the original returns from these functions.
- Original returns and subnetwork list are extracted as individual objects upon completion of functions nwm_route and compute_nhd_routing_v02 so as to not interfere with ensuing operations to results.
-
-
1. Tested that code …
> edits to only calculate subnetworks on first iteration of for loops

- src/troute-network/troute/nhd_network_utilities_v02.py
- src/troute-nwm/src/nwm_routing/preprocess.py
When a single diffusive domain is applied for the hybrid routing in t-route, python dictionary refactored_reaches takes its values as a list of lists of reaches of diffusive mainstem domain. However, when multiple diffusive domains are applied, the dictionary values were somehow melted down to a list of a single list of all diffusive mainstem segments except downstream end segments of tributaries entering the mainstem.  This should be still the same format as a list of lists.  This is solved now.
- Python dictionary refactored_reaches_batch takes a list of lists for each diffusive mainstem defined by a given TW and then keep the form in Python dictionary refactored_reaches. 
-
-
1.
-
-
> solve roredered_reaches issue when two independent diffusive mainstem domains are applied

- src/kernel/diffusive/diffusive.f90
- src/kernel/diffusive/pydiffusive.f90
- src/troute-network/troute/nhd_io.py
- src/troute-nwm/src/nwm_routing/__main__.py
- src/troute-nwm/src/nwm_routing/output.py
- src/troute-nwm/src/nwm_routing/preprocess.py
- src/troute-routing/troute/routing/compute.py
- src/troute-routing/troute/routing/diffusive_utils.py
- src/troute-routing/troute/routing/fast_reach/diffusive.pyx
- src/troute-routing/troute/routing/fast_reach/fortran_wrappers.pxd
- src/troute-routing/troute/routing/fast_reach/pydiffusive.h
Mapping back water elevation from refactored to unrefactored hydrofabric was performed by interpolation water elevation, but this estimation occasionally produce negative water depth due to discrepancy in thalwegs between refactored and unrefactored hydrofabrics. Now, the interpolation is performed on water depth instead to solve this issue. 
-
-
-
1.
-
-
> Map back water elevation from refactored to unrefactored hydrofabric by interpolating water depth not elevation

- src/troute-network/setup.py
- src/troute-network/troute/AbstractNetwork.py
- src/troute-network/troute/DataAssimilation.py
- src/troute-network/troute/HYFeaturesNetwork.py
- src/troute-network/troute/NHDNetwork.py
- src/troute-network/troute/nhd_network.py
- src/troute-routing/setup.py
Add a base abstract class for a network, and implementations for both NHD and HY Features.
Manually cherry picked and patched the three classes so that they are consistent with the HEAD of the ngen branch.
The next steps will to look at 3b64c41e04e7a690bcef7c73fb952b0f94f1c964 and see how, at the time, `__main__` was refactored to use these structures.  From there, we can extend these data structures as needed and look at refactoring the current entry point to use them.
Along the way, it may be worth looking alt `nhd_io` and `nhd_network` and `nhd_network_utilities` to see what can be moved around and/or deprecated from those modules
- AbstractNetwork
- NHDNetwork
- HY_FeaturesNetwork
- Added a deprectation warning to extarct_waterbody_connections
1. None, yet =(
- This should remain in …
> troute network abstractions for NHD and Hy Features based networks

- src/troute-network/troute/DataAssimilation.py
Updates to DataAssimlilation.py to create a data_assimilation object containing all the necessary DA information. This implementation defines a single DA class, 'AllDA', that creates all of the DA dataframes and dictionaries (e.g., lastobs_df, usgs_df, reservoir_usgs_df, etc.) that are needed based on user input. All of the logic regarding which DA options to use are performed within the AllDA class definition.
I've tested that calling AllDA(...) creates identical dataframes as those in the current implementation of t-route. I used the standard_AnA.yaml configuration file for these tests.
- import additional necessary modules
- _reindex_link_to_lake_id function to replace link ID index values with lake ID
- _create_usgs_df function to create dataframe of USGS gage observations from USGS …
> Da abstract classes

- src/troute-network/troute/hyfeature_network_utilities.py
- test/unit_test_hyfeature/unittest_hyfeature.yaml
Added capability to convert nexus qlat csv files output by ngen (single file per nexus with all timesteps) into hourly parquet files (one file for every hour containing all nexus points) that conforms to t-route's current method of reading qlat input data.
- If file filter for qlat input data is "nex-", these csv files will be read in and converted into hourly parquet files. These files are saved in a directory designated by new "binary_nexus_file_folder" parameter under "forcing_parameters" in the config file.
- Updates the "nexus_input_folder" and "nexus_file_pattern_filter" parameters to reflect the new parquet directory/files
- Runtime errors are raised if the binary_nexus_file_folder is not provided, does not exist, or is not empty.
- Update method of reading qlat files to be able to …
> Reformat qlat inputs

- src/troute-nwm/setup.cfg
Make sure the setup.cfg knows how to properly find the actual package under the `src` dir.  Otherwise, a standard install (`pip install troute-nwm/`) won't actually install the module source required (`-e` works/ed cause it just created a link to the src dir, but for actual packaging, it doesn't bundle the package code without this in the config.
For reference, check out [this useful reference on src/ layouts](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#using-a-src-layout)
> Fix troute-nwm package setup.cfg

- compiler.sh
- src/kernel/diffusive/makefile
- src/kernel/muskingum/makefile
- src/kernel/reservoir/makefile
- src/troute-network/setup.py
- src/troute-network/troute/network/reservoirs/levelpool/levelpool_structs.c
- src/troute-network/troute/network/reservoirs/rfc/rfc_structs.c
- src/troute-routing/setup.py
Believed minimal set of changes to allow compilation with Intel (other?) compilers.
- Mainly added the ability to specify the compiler and build environment settings via environment variables
- Some capability to control compiler flags to Cython extension building pipelines
- A few `void` return types that weren't C-spec that the compilers complained about
- Explicit references to gcc, gfortran, libgfortran etc.
- Nothing functional
1. Tested with Intel OneAPI 2022.3.0 and also with GCC8 suite.
2. Integration test on [NOAA-OWP/ngen](https://github.com/NOAA-OWP/ngen/actions/runs/4512264572/jobs/7945473202)
3. Test case added that can be used with ngen+t-route master branch in `data/gauge_01073000` in [ngen PR#502](https://github.com/NOAA-OWP/ngen/pull/502/files)
-
-
> Build system updates for Intel compilers

- src/troute-network/troute/HYFeaturesNetwork.py
Creates empty dataframes for waterbody_df and waterbody_types_df if no valid waterbody layer are found in the geopackage
- try/except logic while reading waterbody layers in geopackage
- if there are no waterbody parameters, create empty waterbody dataframes.
-
-
1.
-
-
> default creation of empty waterbody dataframes

- src/bmi_reservoirs.py
- src/bmi_troute.py
- src/troute_model.py
- test/BMI/run_bmi_persistence_example.py
Updates to bmi_troute and troute_model so we can retrieve flowveldepth dataframe as a 1d array after every call of update(). This will be used to connect separate networks by pulling the flowveldepth values calculated in an upstream network and passing these values to the downstream network.
- New bmi variable, 'fvd_results'
- Populate fvd_results after every update call with a 1d array.
- Updates to run_bmi_persistence_example file
-
-
1.
-
-
> Updated get_values() functionality

- src/kernel/diffusive/diffusive.f90
I was reading through the code and encountered a typo, so I systematically sought to fix them.
- The code itself spells `froud` though the name is Froude. I didn't change the variable names (cf https://en.wikipedia.org/wiki/Froude_number)
> Fix typos found by running ispell on comments and strings

- src/troute-network/troute/nhd_io.py
Numpy v 1.20 deprecated and removed `numpy.str``, this update explicitly uses `numpy.dtype.str` do specify the dtype.
> update use of numpy str dtype

- doc/v3_doc.yaml
I found a few bugs/typos in `v3_doc.yaml`. This PR resolves the issues I found.
Bugs / Typos:
- The configuration option key, `usace_timeslices_folder`, was missing and double listed as `usgs_timeslices_folder`.
- Listed default option for `wrf_hydro_channel_restart_pattern_filter` was `HYDRO_RST*` but should have been `HYDRO_RST.*`.
> Fix bugs in v3_doc.yaml

- src/troute-network/troute/nhd_io.py
The fix in #623 served only to mute the module attribute/reference issue of `numpy.str` being deprecated.  The `numpy.dtype.str` isn't a suitable replacement of `numpy.str`, as the `str` attribute here, according to the docs, is
```
attribute
dtype.str
The array-protocol typestring of this data-type object.
```
which is not a compatible [string datatype](https://numpy.org/doc/stable/reference/arrays.dtypes.html#string-dtype-note).  The below error seen when using this as a `dtype` has been similarly reported while trying to run t-route since merging #623.
It seems that native python types are reasonably supported, though they may not be the most efficient.  Using `str` for the `astype` arg should work, as seen below, this converts to a unicode string.
```sh
Successfully installed …
```
> actually fix numpy str type deprecation

- src/troute_model.py
Time log is added that record the time for creating a network, forcing, run time, data assimilation and at the end output the results.
-
-
-
1.
-
-
> Time log based on new update

- src/troute-routing/troute/routing/fast_reach/mc_reach.pyx
the returned values broke down to be more readable and nudge value added
-
-
-
1.
-
-
> nudged value added in return

- src/troute-network/troute/AbstractNetwork.py
- src/troute_model.py
Quick fix so preprocessing parameters are an input to HYFeatures in troute_model.py
- preprocess parameters for HYFeatures using BMI
- Check for `from_files` before building qlateral array
-
1.
-
-
> Fix preprocess param issue

- compiler.sh
- src/troute-network/setup.py
- src/troute-network/troute/nhd_io.py
- src/troute-routing/setup.py
> Build package updates

- compiler.sh
By adding missing editable/no-editable functionality to network-config. This should solve the #651 issue.
- Enabled editable/no-editable functionality to network-config in [compiler.sh](https://github.com/NOAA-OWP/t-route/pull/657/files#diff-2ca6ed5bcf5279d22de0a0f3962be15b6870911788ec741a980b63c9e84765d5)
1. Installation testing:
```bash
./compiler.sh no-e
```
> adding missing editable/no-editable functionality to network-config

- src/troute-network/troute/HYFeaturesNetwork.py
Generalizes bandaid() function that fixes missing lake_id-segment connections in hydrofabric. Originally designed for CONUS, but now it is generalized to work on subdomains when these segments/waterbodies are not in the domain.
-
-
- Edit bandaid() function in HYFeatures.py
1.
-
-
> generalize bandaid() function to work on subdomains of CONUS

- src/troute-network/troute/HYFeaturesNetwork.py
Remove any waterbodies from waterbody_df that have missing parameters. We cannot compute reservoir routing without these params.
-
-
- Drop rows with missing values in waterbody_df
1.
-
-
> drop waterbodies with missing parameters

- readme.md
- src/troute-nwm/src/nwm_routing/preprocess.py
Fix for #658 #617
breakout from #660 
- Updates dataframe joins in preprocessing.py to always drop the index _**regardless of the name**_. Fixes index not found error.
- Updates main README.md test command to include the required -V3 argument
1. Tested on rockylinux:9.2 using a docker image #669 
```bash
Traceback (most recent call last):
File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/opt/venv/lib64/python3.9/site-packages/nwm_routing/__main__.py", line 2025, in <module>
main_v03(v_args[1])
File "/opt/venv/lib64/python3.9/site-packages/nwm_routing/__main__.py", line 1439, in main_v03
) = nwm_forcing_preprocess(
File …
```
> -V3 test fix

- src/troute-network/troute/HYFeaturesNetwork.py
- src/troute-network/troute/nhd_io.py
Fix some issues with writing flowveldepth files and LAKEOUT files
- Add lat, lon, and crs info to waterbody_dataframe. Writing LAKEOUT files requires this info. Does not change any routing computations.
-
- Check if `usgs_positions_id` array is empty. If so, simply write -9999.0 values for all `nudge` values
- Change printing 'wrote such and such file' to a LOG.debug feature.
1. Worked on LowerColorado_TX_v4 HYFeatures
-
-
> Repair output functions

- requirements.txt
Fixes #651
breakout from #660 
Adds required pip packages to requirements.txt
Locks cython version to fix ./compile.sh
- pyarrow
- deprecated
- geopandas
- Cython==0.29.36
```bash
#0 65.83 Compiler crash traceback from this point on:
#0 65.83   File "/opt/venv/lib64/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 4968, in analyse_types
#0 65.83     performance_hint(index.pos, "Index should be typed for more efficient access")
#0 65.83 TypeError: performance_hint() missing 1 required positional argument: 'env'
#0 65.83 Traceback (most recent call last):
#0 65.83   File "/t-route/src/troute-routing/setup.py", line 122, in <module>
#0 65.83 Fortran compiler type is: gnu95
#0 65.83 Compiling troute/routing/fast_reach/reach.pyx because it changed.
#0 65.83 Compiling …
```
> fix - lock cython version, add missing pip deps

- src/troute-network/troute/AbstractNetwork.py
- src/troute-network/troute/HYFeaturesNetwork.py
- src/troute-network/troute/nhd_io.py
- src/troute-nwm/src/nwm_routing/__main__.py
t-route now checks if LAKEOUT files are too be created (set in yaml file under output_parameters -> lakeout_output:) before performing re-projection of waterbody_dataframe to get latitude, longitude, and crs information. 
This is an issue that arose due to sqlite3 versioning. This doesn't actually fix that problem, but is a workaround for now.
AbstractNetwork.py
- add `output_parameters` slot
HYFeaturesNetwork.py
- Check if LAKEOUT files are to be created. If so, reproject geopandas.dataframe geometry column to get lat, lon, and crs columns
- If not creating LAKEOUT files, assign those columns np.nan
- Unrelated, but fix `pd.DataFrame.set_index()` error for `gage_df `
AbstractNetwork.py
- add `output_parameters` as input to `HYFeatures()`
-
-
1.
-
-
> Check before performing CRS reprojection

- src/model_DAforcing.py
Added lite-restart and lastObs, along the lines of last additions (usgs, usace, etc). Abstract classes will be created at a later stage upon more-complete integration into t-route. 
-
-
-
1.
-
-
> Adding lite-restart and lastObs to BMI conversions

- src/troute-network/troute/DataAssimilation.py
- src/troute-nwm/src/nwm_routing/__main__.py
- test/LowerColorado_TX_v4/test_AnA_V4_HYFeature.yaml
When from_files is still True (which means not using BMI), it creates rfc_df and rfc_param_df only to use Python version of RFC DA because Fortran RFC DA keeps causing Deallocate related error.
-
-
-
1.
-
-
> use only python version of RFC DA

- src/troute-network/troute/DataAssimilation.py
Adds `_rfc_timeseries_df` slot in DataAssimilation.py. Should fix [this comment](https://github.com/NOAA-OWP/t-route/pull/688#issuecomment-1809200162)
-
-
-
1.
-
-
> add _rfc_timeseries_df slot

- src/troute-config/troute/config/config.py
- src/troute-config/troute/config/network_topology_parameters.py
- src/troute-network/troute/HYFeaturesNetwork.py
Added ability for t-route to read network information from json and geojson files. These changes have only been implemented for input files that contain network and nexus information, not waterbody or data assimilation info.
config.py
- Added `@root_validator` to check if the .yaml file contains a .json file for `flowpath_edge_list` if the `geo_file_path` is a .json file.
-
network_topology_parameters.py
- Made `waterbody:`, `alt:`, and `gages:` parameters under `columns:` optional
- Added optional `flowpath_edge_list:` parameter
HYFeaturesNetwork.py
- Updated `read_json()` function to be flexible in handling the names of `id` and `toid`
- Added `read_geojson()` function
- Updated `read_geo_file()` function to choose between reading .gpkg, .json, or .geojson files
- Moved renaming of …
> Read json/geojson files

- src/troute-config/troute/config/config.py
- src/troute-nwm/src/nwm_routing/__main__.py
Redo a modification to how `output_parameters['lite_restart']` is checked prior to calling `write_lite_restart` in `__main__.py`.
This change existed, but was undone in [PR#695](https://github.com/NOAA-OWP/t-route/pull/695)
-
-
__main__.py
- Check if `output_parameters['lite_restart']` is not `None`
config.py
- Add `@root_validator` to ensure a `lite_restart_output_directory` is provided if `lite_restart` is not `None`
1.
-
-
> fix checking for lite_restart and config test for lite_restart_directory

- src/troute-routing/troute/routing/compute.py
- src/troute-routing/troute/routing/diffusive_utils_v02.py
The current diffusive_utils.py includes features utilizing refactored hydrofabric that was originally developed for removing short stream segments of NHDv2.0 hydrofabric of NWMv3.0.  The removal was mainly for reducing routing compute time and possible numerical instability.   The development of refactored hydrofabric wasn't completed and was stopped. Now the nextgen HYfeature hydrofabric replaces the refactored hydrofabric, so features related to the refactored hydrofabric aren't needed any more.   So the cleaned diffusive_utils_v02.py is created to be used for both NHDv2.0 hydrofabric and HYfeature hydrofabric.   More features to come in this file for HYfeature pretty soon.
-
-
-
1.
-
-
> A new diffusive_utils file  without features designed only for refactored hydrofabric 

- src/troute-network/troute/AbstractRouting.py
- src/troute-routing/troute/routing/diffusive_utils_v02.py
This update read the parquet file. It checks if `topobathy_domain` is netdf or parquet and if its parquet clean it up. Including separating just cs_id = 1 which is the cross-section for upstream of each segment and drop the None values.
- `read_parquet` function file that read, clean and return the parquet file
- edit in the `topobathy_df` property function to read topobathy_df with extension of `.parquet`
-
-
1.
-
-
> update to read the parquet file

- src/troute-network/troute/AbstractNetwork.py
Mostly Resolves performance issues mentioned in #713 
- Restructured operations to perform most of the file manipulation with bash commands instead of expensive python operations
```pseudocode
for each nexus file
read as csv
format and pivot data
for each timestep
open the parquet for that timestep
write one entry to the parquet
close the parquet
```
```pseudocode
for each nexusfile
bash command to split csv as plaintext into timestep files
for each timestepfile
read timestepfile csv
convert timestepfile to parquet
save parquetfile
```
The data is still being written the same amount of times, but it's mostly plaintext appends which bypasses the expensive parquet IO  until the final pass.
[data I used](https://ciroh-ua-ngen-data.s3.us-east-2.amazonaws.com/AWI-002/AWI_03W_113060_002.tar.gz) …
> Nex to bin speedup

- src/troute-network/troute/AbstractRouting.py
- src/troute-routing/troute/routing/diffusive_utils_v02.py
3D channel cross section data currently being developed for diffusive mainstem domains has missing topobathy data for some flowpaths in the domains.  The 3D data is based on v20.1 hydrofabric gpkg.  To temporarily fix this issue while waiting for more solid update, a simple solution was applied to fill the gap: Basically, a flowpath with no available topobathy data, it borrows the data from the closest upstream flowpath.  If the upstream has multiple topobathy data available, then it borrows the most downstream topobathy data.   Again, this is a simple and temporary solution for making diffusive module functionally run  and need to be updated along the way.
-
-
-
1.
-
-
> simple fix for flowpaths with unavailable 3Dxsec data

- src/troute-network/troute/AbstractNetwork.py
- src/troute-network/troute/AbstractRouting.py
- test/LowerColorado_TX_v4/domain/coastal_domain_LC_US_DS.yaml
A function added that build diffusive_domain using given headwater, tailwater segment IDs from the yaml file, so user don't need coastal_domain yaml file. It will be created automatically. 
-
-
-
1.
-
-
> function that build diffusive domain

- src/troute-network/troute/NHDNetwork.py
- src/troute-network/troute/nhd_io.py
1- Small updates on how it reads the `coastal_subset.txt`, now if we comment it out in yaml file it won't give error.
2- Change on how it reads the `LAKEPARM` file, if we don't have lake or just one id it won't crash
-
-
-
1.
-
-
> updates to run NHD

- src/troute-network/troute/HYFeaturesNetwork.py
fixes #724
- fix bug in `HYFeaturesNetwork.preprocess_waterbodies`. Now always drop `waterbody` column from `HYFeaturesNetwork.dataframe` (network DataFrame) (fixes #724).
> Always drop waterbody col from network df

- src/troute-network/troute/AbstractNetwork.py
See #720 for more detail.
- `AbstractNetwork.split_csv_file` is now mac and unix compliant (Fixes #720).
> `awk` call is now gnu and bsd compliant. fixes #720

- src/troute-network/troute/nhd_io.py
- src/troute-network/troute/nhd_network.py
usgs gages is in byte string and before the code was not converting it to normal string. So the updated code convert it to normal string.
-
-
-
1.
-
-
> Update on NHD to convert byte string to normal string

- src/troute-routing/troute/routing/compute.py
The empty `nudge` array that was returned from `compute_diffusive_routing()` had no shape, so an error was thrown when attempting to concatenate nudge values in `write_flowveldepth_netcdf()` on output. This assigns the proper shape to the `nudge` array.
-
-
**compute.py**
- return an empty numpy array of shape `(0, nts)`. 
1. Successfully ran a domain with multiple diffusive domains and wrote output files.
-
-
> Make empty nudge array returned from diffusive the proper size

- src/bmi_troute.py
- src/troute-network/troute/AbstractNetwork.py
- src/troute-network/troute/HYFeaturesNetwork.py
- src/troute_model.py
t-route will now read the 'nexus' attribute table from the HYFeatures geopackage if diffusive routing is enabled. From this table, the latitude and longitude of all diffusive domain tailwater nexus points are determined and stored in the `values` BMI dictionary. These will be used to advertise geospatial locations to the model engine which can then determine the closest coastal model nodes to be used for diffusive boundary conditions.
**HYFeaturesNetwork.py**
- Read "nexus" attribute table if diffusive routing is enabled
- Store this table as a data frame for later processing
**AbstractNetwork.py**
- Filter "nexus" data frame to only diffusive domain tailwater nexus points
- Reproject `geometry` column to be lat/lon friendly.
**bmi_troute.py**
- Create empty arrays for diffusive tailwater …
> Diffusive tailwater latitude/longitude information

- src/troute-routing/troute/routing/diffusive_utils_v02.py
Running NHD was giving 2 Warning. first warning was `FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead` which line 41 handle that.
The other warning was for concatenating empty dataframe `FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.`
which line 545 checks if its empty won't concatenate it.
With these two minor changes there is no warning
-
-
-
1.
-
-
> Handling Warnings

- src/troute-network/troute/AbstractRouting.py
- src/troute-network/troute/DataAssimilation.py
- src/troute-nwm/src/nwm_routing/output.py
This fix provides a solution when lastobs_df is empty because no usgs data is available while stream nudging is unknowingly activated in the config file. More solid solution will be provided soon.  Also, in diffusive_routing mainstem_list now has a list  of stream segments aligned in order from upstream to downstream.  Moreover, missing topobathy data for a stream segment get filled in by looking up the newly aligned list.
**AbstractRouting.py**
- removed sort() to mainstem_list to align a list of stream segments in order from upstream to downstream
- modified the way to search for an upstream segment id for a given mainstem segment that has no channel xsec topobathy data
**DataAssimilation.py**
- Added a condition not to call new_lastobs function when there is no lastobs related values …
> simple fix for empty lastobs_df when streamnudging unknowingly turned on while no usgs data is available

- .gitignore
- src/troute-network/troute/AbstractNetwork.py
Fixes how t-route retrieves water depth from SCHISM output files. It now reads both `elevation` and `depth` variables and sums them to get water depth. 
-
-
**AbstractNetwork.py**
- `read_SCHISM_output()` now adds `elevation` and `depth` variables from netcdf file to obtain water depth.
**.gitignore**
- added `*.mod`, `*.a`, & `*.c` to reduce output when `git status` is called. This is unrelated to coastal boundary information.
1.
-
-
> Correction to reading schism data from file

- src/kernel/diffusive/diffusive.f90
- src/kernel/diffusive/pydiffusive.f90
- src/troute-routing/troute/routing/compute.py
- src/troute-routing/troute/routing/fast_reach/diffusive.pyx
- src/troute-routing/troute/routing/fast_reach/fortran_wrappers.pxd
- src/troute-routing/troute/routing/fast_reach/pydiffusive.h
diffusive fortran kernel (diffusive.f90) has been outputting discharge and water elevation (from a given datum) so far. This commit adds an additional output variable for computed water depth to be consistent with returned variables of Muskingum-Cunge module.  
- diffusive.f90: New returned variable depth_ev_g takes computed water depth values for each computation node (For example, one stream segment has one compute node at the upstream end and the other at the downstream end.   Consecutive stream segments share a common compute node that is either the lower end node of an upstream stream segment or the upper end node of the downstream stream segment.
- pydiffusive.f90:  added depth_ev_g accordingly.  
- diffusive.pyx:  added depth_ev_g and out_depth accordingly
- fortran_wrapper.pxd: …
> add water depth output variable to diffusive fortran kernel

- src/troute-config/troute/config/output_parameters.py
`typing.Annotated` was introduced in python 3.9. Use `typing_extensions.Annotated` to support older versions of python.
> fix: support python 3.8

- src/troute-network/troute/DataAssimilation.py
- src/troute-network/troute/NHDNetwork.py
- src/troute-network/troute/nhd_io.py
- src/troute-network/troute/nhd_network.py
- src/troute-nwm/src/nwm_routing/preprocess.py
There was inconsistent handling of converting USGS gage IDs from byte strings to character strings. This resulted in link-gage-crosswalk and lake-gage-crosswalk having different character representations of the same gage IDs. The position where `_reindex_link_to_lake_id()` function was also caused issues as it replaced link IDs with lake IDs in `usgs_df` before creating `reservoir_usgs_df`. This resulted in missing lake IDs/gage IDs in `reservoir_usgs_df`.
-
-
**DataAssimilation.py**
- Moved location of `_reindex_link_to_lake_id()`
**NHDNetwork.py**
- Updated accessing `reservoir_da` parameters to conform to config-module. This incorporates changes from PR #737
**nhd_io.py**
- Convert gage ID byte strings to character strings in a consistent way.
**nhd_network.py**
- Convert gage ID byte …
> Fix NHD issues related to gage byte strings

- src/troute-network/troute/AbstractNetwork.py
- src/troute-network/troute/HYFeaturesNetwork.py
- src/troute-network/troute/nhd_io.py
- src/troute-nwm/src/nwm_routing/output.py
Some changes to speed up writing output files, specifically flowveldepth netcdf for runs with many timesteps.
Enable t-route to use nex-* file as a forcing file, and only convert/write parquet files if `binary_nexus_file_folder` is provided.
-
-
-
1.
-
-
> Speed up output

- src/troute-network/troute/nhd_io.py
Fix setting `num_files` to 1 if it is 0. It can be zero if the timesteps within `flowveldepth` are less than the `stream_output_time` parameters. A value of 0 would write no output, but 1 will at least write a single output file.
-
-
-
1.
-
-
> fix setting 'num_files' to 1 if it is 0

- src/troute-config/troute/config/network_topology_parameters.py
- src/troute-network/troute/HYFeaturesNetwork.py
- test/LowerColorado_TX_v4/domain/coastal_domain_tw.yaml
Quick updates to config module/retrieval. Set default values for `columns` if user leaves this parameter blank. This includes a `@validator` to set defaults based on whether it is a `NHDNetwork` or `HYFeaturesNetwork`. 
Also fixed retrieving `rfc_da` parameters in `read_geopkg()` function. This was looking for these parameters in `waterbody_parameters` which was the old method. Now looks in `data_assimilation_parameters` where they actually are for V4.
**network_topology_parameters.py**
- Default values for `columns` for both NHD and HYFeatures networks
- `@validator` to set appropriate default values based on `network_type`
-
**HYFeaturesNetwork.py**
- Updated where `rfc_da` parameters are retrieved from
1.
-
-
> Fix config issues relating to 'columns' default values and retrieving rfc da parameters

- src/kernel/diffusive/diffusive.f90
Too high values of the celerity in the diffusive Fortran kernel often lead to too small (sometimes several orders of magnitude smaller than on second), which virtually freezes the kernel.  To prevent it from happening, upper limits on celerity are placed after deriving from the Courant condition with minimum simulation time increment being initially given time step divided by an  user-provided numeric value (10 in this case). 
diffusive.f90: Once validated, the user-provided numeric value, for better use, should be directly passed from config yaml or through diffusive_util_v02.py 
-
-
1.
-
-
> Upper limit on celerity value in diffusive Fortran kernel

- src/kernel/diffusive/diffusive.f90
- src/kernel/diffusive/pydiffusive.f90
- src/troute-network/troute/AbstractRouting.py
- src/troute-routing/troute/routing/diffusive_utils_v02.py
When defining diffusive domain including not only mainstem but also connected tributaries by [this config file](https://github.com/NOAA-OWP/t-route/blob/master/test/LowerColorado_TX_v4/domain/coastal_domain_tw.yaml), diffusive.f90 hasn't been executed diffusive wave routing on all the reaches where the config file defines to run diffusive wave on. That's because diffusive.f90 assumes a reach without any its upstream reach to not run diffusive wave on but instead to  already have given flow and depth data computed from other routing model, in this case MC.  By defining a reach of index j in frnw_g with specified value, for example, 555 for diffusive reach while -555 for already-computed reach,  diffusive.f90 now correctly route on all reaches told to run diffusive wave. …
> Diffusive fortran kernel correctly executes diffusive wave on stream segments defined by Python preprocessing

- src/troute-network/troute/AbstractRouting.py
`all_links` object was causing errors when diffusive was run not using the `999999` flag (so just on a mainstem). This fixes those issues.
-
-
-
1.
-
-
> Fix all_links object when running diffusive on just the mainstem

- src/kernel/diffusive/diffusive.f90
When trying to make both conveyance and dK/dA curve against water elevation monotonically increasing to avoid discontinuous or irregular shapes, finding next larger data points sometimes fails. In this case, an artificially and linearly increasing line is instead used to estimate the  new values of conveyance or dK/dA over not monotonically increasing areas.  
- diffusive.f90: Such linear interpolation is implemented over to not monotonically increasing parts of the curves of both conveyance and dK/dA  
-
-
1.
-
-
> Make smoothing conveyance and dK/dA curves of xsec lookup table of diffusive wave more robust

- src/troute-network/troute/nhd_io.py
- src/troute-routing/troute/routing/diffusive_utils_v02.py
The function that save outputs updated to be able to save in csv and pickle format. User just need to make change in yaml file to select the format
- a function named `write_flowveldepth_csv_pkl` added that saves in csv and pickle formats
-
-
1. Tested with different time frequency and compared with netcdf file
-
-
> update to save other formats

- src/troute-network/troute/AbstractRouting.py
- src/troute-network/troute/HYFeaturesNetwork.py
- src/troute-nwm/src/nwm_routing/__main__.py
- src/troute-nwm/src/nwm_routing/output.py
Two major updates:
1. Fix issue of duplicate integer IDs between some waterbodies and stream segments. We now add a large number to any duplicate waterbody ID initially, then revert back to the original ID before writing output files.
2. Some waterbodies have flowpaths that physically lie within them, but are not referenced to the waterbody ID. This causes issues when collapsing segment IDs into a single waterbody ID in our connections dictionary (multiple "downstream" IDs which violates the DAG). These waterbodies are simply "dropped" as waterbodies, meaning the underlying segments are used for MC routing.
-
-
**AbstractRouting.py**
- Updates to finding outlet IDs of waterbodies. The old method became an issue for a waterbody in Florida that directly flows into the ocean. …
> Updates to handle problematic waterbody data

- src/troute-network/troute/HYFeaturesNetwork.py
Set the default value for `_duplicate_ids_df` to an empty `pd.DataFrame()`
-
-
**HYFeaturesNetwork.py**
- Set the default value for `_duplicate_ids_df` to an empty `pd.DataFrame()`
1.
-
-
> Default _duplicate_ids_df to empty data frame

- src/troute-config/test/test_types.py
`FilePath` and `DirectoryPath` build on pydantic's `FilePath` and `DirectoryPath` classes. Specifically, `troute.config`'s version of these classes unable using a "strict" mode (see committed tests for usage). The idea of strict mode is that in some contexts it is desirable to verify if a file or directory path exists. Likewise, in other contexts that is not desirable. "strict" mode enables the best of both worlds by effectively toggling if existence is verified.
To run the tests (assuming you've cloned the repo and you are in the repo root):
```shell
pip install 'src/troute-config[test]'
pytest src/troute-config
```
> Add tests for `troute.config.FilePath` and `troute.config.DirectoryPath`

- compiler.sh
- readme.md
- src/troute-network/pyproject.toml
- src/troute-nwm/pyproject.toml
- src/troute-routing/pyproject.toml
- src/troute-routing/troute/routing/compute.py
[`pip` `23.1`](https://pip.pypa.io/en/stable/news/#id80) changed the default behavior when the `wheel` package is not installed. `troute.network` and `troute.routing` both require `wheel` at build time and previously did not contain `pyproject.toml` files.
> When the `wheel` package is not installed, `pip` now uses the default build backend instead of `setup.py install` and `setup.py develop` for project without `pyproject.toml`. ([#8559](https://github.com/pypa/pip/issues/8559))
The PR addresses these issues and makes it possible to install `troute` using the latest `pip` version (`24.0`).
Fixes #621.
> `pip>23.1` compliance

- requirements.txt
Should have added this in #780. This should fix [the CI docker image build failures](https://github.com/NOAA-OWP/t-route/actions/runs/9457679519/job/26051934655).
> Add build dep `wheel` to `requirements.txt`

- src/troute-network/troute/HYFeaturesNetwork.py
Assert a known unrecoverable condition and provide a more informative user error message. See #721 for more information.
Fixes #721
- `troute.network` now raises an assertion error and provides an informative user error message when duplicate `feature_id`s are present in a NextGen catchment or nexus output file. (see #721).
> style: improve `InvalidIndexError` error message

- src/troute-network/troute/AbstractNetwork.py
- src/troute-network/troute/AbstractRouting.py
routing_scheme_map in AbtractNetwork.py was updated to run diffusive when using channel topobathy data was turned off in the config yaml file.  Now when "run_hybrid_routing" and "use_natl_xsections" are True and False, respectively, t-route run MC+diffusive both with synthetic xsec data provided by RouteLink file.
-
-
-
1.
-
-
> fix for diffusive to run with synthetic and topo on NHD

- src/troute-network/troute/AbstractNetwork.py
Remove raising an error if parquet files already exist in the provided binary_folder.
-
**AbstractNetwork.py**
- `elif` check for existence of parquet files, which would then raise an error.
-
1.
-
-
> Remove check for existing parquet files

- src/troute-config/troute/config/bmi_parameters.py
- src/troute-config/troute/config/compute_parameters.py
- src/troute-config/troute/config/config.py
- src/troute-config/troute/config/logging_parameters.py
- src/troute-config/troute/config/network_topology_parameters.py
- src/troute-config/troute/config/output_parameters.py
- src/troute-network/troute/DataAssimilation.py
- src/troute-nwm/src/nwm_routing/__main__.py
- src/troute-nwm/src/nwm_routing/input.py
- src/troute-nwm/src/nwm_routing/log_level_set.py
- src/troute-routing/troute/routing/compute.py
- test/LowerColorado_TX/test_AnA_V4_NHD.yaml
- test/LowerColorado_TX_v4/test_AnA_V4_HYFeature.yaml
- test/LowerColorado_TX_v4/test_AnA_V4_HYFeature_noDA.yaml
Added better default values for several parameters. Removed `extra='forbid'` limitation everywhere.
-
-
-
1.
-
-
> Simplify config module

- doc/util/gen_config_docs.py
Adds a CLI script that generates documentation in yaml format from a `pydantic` model (e.g. `troute.config.Config`). A field's name, type annotation, and "docstring" will be used to generate the documentation. Example:
```python
from pydantic import BaseModel
class Bar(BaseModel):
baz: int
"""
The baz field holds the number of quox in the observable universe.
"""
```
```shell
python gen_config_docs.py foo.Bar
baz: int
```
I've verified that this tool works to generate documentation for `troute.config.Config`. Hopefully, this will remove some of the burden in writing up documentation 😃!
<details><summary><code>python gen_config_docs.py troute.config.Config</code> output</summary>
Note, at the moment there are not doc strings on fields, so no rich documentation is generated.
```shell …
```
> feat(docs): add CLI tool for generating troute config documentation from source

- src/troute-config/troute/config/__init__.py
- src/troute-config/troute/config/output_parameters.py
See #793 for greater detail.
- `ChanobsOutput` field, `chanobs_filepath` does not need to exist at startup. (fixes #794; thanks @program-- :tada:!)
> Fix #793: `chanobs_filepath` does not need to exist at startup

- src/troute-network/troute/AbstractNetwork.py
Removes breaking t-route if a forcing .parquet file already exists. This was a safety measure in the original creation of the forcing conversion method, but is not needed. Now t-route will simply overwrite any existing parquet file that shares a name (for new ngen runs)
-
-
**AbstractNetwork.py**
- Remove raising exception of parquet file path already exists.
1.
-
-
> remove raising exception of forcing parquet file already exists

- src/troute-config/troute/config/__init__.py
- src/troute-config/troute/config/compute_parameters.py
- src/troute-config/troute/config/config.py
fixes #799
- If `reservoir_rfc_forecasts` is disabled, the `reservoir_rfc_forecasts_time_series_path` directory will not be validated to exist in strict mode (fixes #799).
@shorvath-noaa, are there other fields that I use this same kind of pattern on? The idea being, that in strict mode, we only _need_ to validate the paths that `troute` will use.
> Don't validate `ReservoirRfcParameters` paths if reservoir forecasts are disabled

- src/troute-network/troute/AbstractNetwork.py
When testing routing for 6500 catchments and 24 timesteps, a large portion of the troute execution time is still spent on reformatting ngen output. PR #714 partially addressed this issue with an awk command. This PR adds multiprocessing to speed it up even more.
```
************ TIMING SUMMARY ************
----------------------------------------
Network graph construction: 0.8 secs,  7.27%
Forcing array construction: 7.7 secs, 69.93%
Routing computations:      1.89 secs, 17.20%
Output writing:            0.61 secs,  5.56%
----------------------------------------
```
```
************ TIMING SUMMARY ************
----------------------------------------
Network graph construction: 0.84 secs, 19.68%
Forcing array construction: 0.98 secs, 22.94%
Routing computations:      1.82 secs, 42.92% …
```
> update csv to parquet to use multiprocessing

- src/troute-config/troute/config/output_parameters.py
- src/troute-network/troute/AbstractNetwork.py
- src/troute-network/troute/DataAssimilation.py
- src/troute-network/troute/NHDNetwork.py
- src/troute-network/troute/nhd_io.py
- src/troute-nwm/src/nwm_routing/__main__.py
- src/troute-nwm/src/nwm_routing/output.py
- test/LowerColorado_TX_v4/test_AnA_V4_HYFeature.yaml
1- By putting `stream_output_time : -1` means it will save all data in one file without considering `max_loop_size`.
2- Also there was a bug in the code that when `max_loop_size` is less than `nts` in the second loop it was giving error that some lake_id can't be found. There was an error in `DataAssimilation` that fixed.
3- If the `stream_output_time` is greater than `max_loop_size` the code was not making correct output, the issue fixed.
-
-
-
1.
-
-
> save in one file

- compiler.sh
- requirements.txt
See #783 for some detail. Ensure that you install `t-route`'s python dependencies with `pip install -r requirements.txt` **before** running `compiler.sh`.
closes #783
@shorvath-noaa, can you give this a try?
> chore(build): fix editable builds

- readme.md
Possible Cython compile errors in T-route caused by PR784 (https://github.com/NOAA-OWP/t-route/pull/784) have resulted in a recommendation to compile in "no-editable' mode (PR 801, https://github.com/NOAA-OWP/t-route/pull/801). The no-e option, in turn, has resulted in the necessity to recompile T-route after each edit of python code. 
The instructions provided here showcase how T-route can be installed in a manner compatible with PR 784 while avoiding the non-editable compile option. It is based on pip and venv, avoiding conda altogether. It has been implemented on WSL, but should be readily adaptable to the same recent long-term stable Ubuntu distros (22.04 and 20.04).
- Instructions in README file
-
-
1.
-
-
> Included pip & venv based instructions for WSL2

- src/troute-config/troute/config/output_parameters.py
- src/troute-nwm/src/nwm_routing/input.py
- src/troute-nwm/src/nwm_routing/output.py
- test/LowerColorado_TX/test_AnA_V4_NHD.yaml
PR to add functionality to output flow, velocity and depth to parquet file. The output parquet is a timeseries data(details in Notes). It is required for the [TEEHR](https://github.com/RTIInternational/teehr) input. TEEHR comprises of set of tools for hydrologic model and forecast evaluation. Storing the t-route output in parquet format will lead to efficient query of the data. Also, it will help in automation by connecting TEEHR with NextGen water model. [CIROH](https://ciroh.ua.edu) along with Lynker has developed a containerized version of NextGen National Water Model [NextGen In A Box (NGIAB)](https://github.com/CIROH-UA/NGIAB-CloudInfra). TEEHR uses DuckDB to query the parquet output from NGIAB stored on cloud.  
- Added functionality to output write flow, velocity and depth to …
> Added functionality to output to parquet 

- src/troute-nwm/src/nwm_routing/output.py
Reworking a `_parquet_output_format_converter` function to speeding it up by vectorizing and using numpy array. Previously it was taking around **50 sec**. Can see in below picture.
But by vectorizing it. It improved to **1 second**.
The result is also checked its the same.
Original function output:
Updated function output:
-
-
-
1.
-
-
> speeding up Parquet_output function by vectorizing

- src/troute-network/troute/nhd_io.py
Update on csv output results. column `t0` and `time` added to just show `current_time`
The output is like below
-
-
-
1.
-
-
> updating time on csv output

- src/troute-config/troute/config/output_parameters.py
Add default values for `prefix_ids` and `configurations`.
-
-
**output_parameters.py**
- `configuration: Optional[str] = 'None'`
- `prefix_ids: Optional[str] = 'wb-'`
1.
-
-
> update default values for parquet output

- src/troute-network/troute/HYFeaturesNetwork.py
This PR improves the speed of `read_geopkg` function, with below changes. :
(It improve the `Duration` by 20% and `CPU Time` by 50%)
1. Optimized Parallel Processing. 
Used `min(cpu_pool, len(layers))` to ensure we don't create more parallel jobs than layers, which avoids unnecessary overhead.
2. Reduced Repetition:
Removed repeated code for reading layers by creating a `read_layer` function.
3. Ensured Efficiency:
Removed unnecessary list creation and directly accessed the `table_dict`.
-
-
Originally it was taking **2.47 sec**
after the changes it takes **1.96 sec** which is **20%** improvement:
1.
-
-
> Optimizing read_geopkg function

- src/troute-network/pyproject.toml
This PR adds `fiona` to the `troute.network` dependencies to handle the case when consumers have `geopandas>=1.0.0` without explicitly installing `fiona`. This change shouldn't impact consumers with `geopandas<1.0.0`, since `fiona` will already be installed.
- Adds `fiona` to troute.network's pyproject.toml dependencies
> troute.network: handle `fiona` dependency for `geopandas>=1.0.0`

- src/troute-config/troute/config/output_parameters.py
In the current implementation, if the user specifies a directory for `stream_output_directory` (e.g., `output/`) that doesn't exist, it results in an error. With the new PR, the code automatically creates the specified directory if it doesn't exist, allowing the output to be saved in that folder without any issues.
-
-
-
1.
-
-
> if the folder doesn't exist

- readme.md
The non-editable flag:
./compiler.sh no-e
is no longer necessary 
(see https://github.com/NOAA-OWP/t-route/issues/675 for details)
-
- non-editable flag from compiler.sh
-
1.
-
-
> Update readme.md: removed obsolete no-e option

- src/troute-network/troute/nhd_io.py
This PR, improve writing output. Before we used `df.apply()` in the aggregation process, which can be slow for large datasets because it iterates over the rows in a less optimized way. To improve performance, we restructured the code by:
**Grouping Without .apply():** Instead of using `apply()`, which is slower, we leveraged vectorized operations like `groupby()` combined with direct masking and conditional aggregation. This allows for more efficient handling of grouped data.
-
-
-
1.
-
-
> Speeding up writing output
