NOAA-OWP/t-route

src/python_routing_v02/compute_nhd_routing_SingleSeg.py

An effort to reduce the amount of dictionary lookups.

Cache dictionary lookups.

---

src/python_routing_v02/compute_nhd_routing_SingleSeg_arr.py
src/python_routing_v02/compute_nhd_routing_SingleSeg_new.py

This PR addresses the ideas presented in #11.
At the moment it is completely untested in terms of accuracy. I've made every effort to keep the computations faithful.
The changes are isolated to a new file as a proof of concept.
@jameshalgren

[WIP] Array based computations

---

contributing.md
src/fortran_routing/mc_pylink_v00/MC_singleRch_singleTS/mc_singleRch_SingleTStep.py
src/fortran_routing/mc_pylink_v00/MC_singleSeg_singleTS/mc_srch_stime_demo.py
src/fortran_routing/mc_pylink_v00/MC_singleSeg_singleTS/mc_sseg_stime_NOLOOP_demo.py
src/python_framework/network_dl.py
src/python_framework/networkbuilder.py
src/python_framework/nhd_reach_parallel_test.py
src/python_framework/nhd_reach_utilities.py
src/python_framework/recursive_print.py
src/python_routing/DynamicReach.py
src/python_routing/MESHpyDUMMYReach.py
src/python_routing/MESHpyReach.py
src/python_routing/SteadyReach.py
src/python_routing/channel_routing_tools.py
src/python_routing/constants.py
src/python_routing/helpers.py
src/python_routing/meshconstants.py
src/python_routing/network.py
src/python_routing/nexus.py
src/python_routing/reach.py
src/python_routing_v02/compute_nhd_routing.py
src/python_routing_v02/compute_nhd_routing_SingleSeg.eval.py
src/python_routing_v02/compute_nhd_routing_SingleSeg.eval_ml.py
src/python_routing_v02/compute_nhd_routing_SingleSeg.py
src/python_routing_v02/compute_nhd_routing_SingleSeg_arr.py
src/python_routing_v02/parallel_compute_nhd_routing.py

Files have been formatted using [black][https://pypi.org/project/black/] to enhance readability, improve style consistency, and reduce diff volume for edits.

Blacken source files

---

src/python_routing_v02/compute_nhd_routing_SingleSeg.py

Attempts to fix the initialization of input parameters. This PR results in repeatable results for me.
~~For the moment, `assume_short_ts` is being disabled.~~
@jameshalgren, would you please look this over and verify that things are initialized to the proper values?

Fix initialization of variables.

---

notebooks/formatnb.py

This script will:
* Clear output cells
* Clear Python metadata
* Try to reformat code blocks with black
ping: @jameshalgren

Script to fixup noteboks prior to committing.

---

src/lookup_routing/NNFullCombos.py
src/lookup_routing/NN_argparse.py
src/lookup_routing/NN_gen_predicted_values.py
src/lookup_routing/NN_gen_training_data.py
src/lookup_routing/NN_gen_val_data.py

Added command line inputs to Neural Net.

added command line inputs to neural net

---

src/fortran_routing/mc_pylink_v00/MC_singleSeg_singleTS/MCsingleSegStime_f2py_NOLOOP.f90
src/python_routing_v01/compute_nhd_routing_SingleSeg.py

netcdf write capabilities added to framework routing (v01)

[WIP] Integrating netcdf write

---

src/python_framework_v01/nhd_network_utilities_v01.py

This is a micro change -- making a pull request to flag the update.

Update link for Main NWM route-link download

---

src/python_framework_v02/nhd_io.py
src/python_framework_v02/nhd_network.py
src/python_framework_v02/nhd_network_utilities_v02.py
src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py

Updates to V02 framework.
* Read waterbody parameters into dataframe
* Extract waterbodies mapping from a dataset
* Add function for querying the shore of a waterbody
* Coalesce waterbody nodes into a single node.
* Query only nodes that belong to a waterbody 
* Function to check if a given node is on the shore of a waterbody
* Reorganize how column information is stored
ping: @jameshalgren

Framework v02 updates

---

src/python_framework_v01/networkbuilder.py
src/python_framework_v02/nhd_io.py
src/python_framework_v02/nhd_network.py
src/python_framework_v02/nhd_network_utilities_v02.py

Catch up blackening

---

src/python_routing_v01/compute_nhd_routing_SingleSeg.py

Comment only; no code change. 
Clarifying the distinction between the time-step sequence and the topology sequence.

Clarify explanation of short-time-step

---

src/python_framework_v01/nhd_network_utilities_v01.py
src/python_framework_v02/nhd_io.py
src/python_routing_v01/compute_nhd_routing_SingleSeg.py

The #142 changes left behind a function reference in the wrong file. 
and
The #137 changes missed a reference to the csv_output flag in the built-in test. 
(We need to implement automated tests asap.)

Bugfix json read nhd io

---

src/python_routing_v01/compute_nhd_routing_SingleSeg.py
test/input/json/CustomInput.json

progress bar for execution timing

---

src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py

Adding command line inputs to accommodate more flexible testing with parallelization, time-steps, etc.

New inputs for v02

---

install.md
src/python_framework_v02/troute/nhd_io.py
src/python_routing_v02/compiler.sh

added instructions for installing the repo
compilation file added
fixed yaml safe_load

Compiler/instructions + yaml.safe_loader

---

install.md
src/python_framework_v02/troute/nhd_io.py
src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py

qlat imports from yaml and cmd line
minor change to install file instructions
need to point this branch to fork not master

qlat read and minor change to install file

---

src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py
src/python_routing_v02/fast_reach/mc_reach.pyx

Looking for insight here. We have several functions that interact with the computation here. I am not sure which parts equate to what in v02 for warm states. Every time I want to add something it's connected elsewhere.

 warm states for V02

---

install.md
src/python_routing_v01/compute_nhd_routing_SingleSeg.py

Just added the download link for the RouteLink_NHDPLUS.nwm.v2.0.4.nc file and its directory.

added troubleshooting for RouteLink_NHDPLUS.nwm.v2.0.4.nc in install.md 

---

src/python_framework_v02/troute/nhd_network_utilities_v02.py
src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py

filtered the q0 dataframe by the mask file ahead of time so we do not run into errors when using multiple restart files.

filtered q0 by mask file 

---

src/python_routing_v02/build_tests.py
src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py

removed redundant arguments nts dt

---

src/python_framework_v02/troute/nhd_network_utilities_v02.py
src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py

same as q0 filtering by mask file but with qlats

qlat filtering by mask file

---

src/python_routing_v02/build_tests.py

Correcting an accidental reversion.

corrected missing args

---

src/fortran_routing/Reservoir_Binding/Reservoirs/makefile
src/fortran_routing/diffusive_v02frwk/makefile
src/fortran_routing/mc_pylink_v00/MC_singleSeg_singleTS/makefile

These minor updates standardize (or attempt to standardize) the implicit variables as used in the various fortran makefiles. 
See https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

Minor makefile standardization

---

src/nwm_routing/src/nwm_routing/__main__.py

Required output block was missing. Made a few additional minor updates.

Output cleanup

---

src/python_framework_v02/troute/nhd_network_utilities_v02.py
src/python_routing_v02/troute/routing/compute.py

replace reach list with type creation with a single common function

---

src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx

Applied a simple file formatter to the cython source to improve the diffs. Similarly to black we can use this in the command line to fix all the cython files with indent errors. 
pip install reindent 
move to directory
reindent {filename}

cython indentation fix

---

src/python_framework_v02/troute/network/reservoirs/test/test_compute_kernel.py
src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx

Setting Routing Period in MC Reach to dt from YAML input file
Removed hard coded routing period of 300 seconds.
Fixes #365 
Tested with Croton LP, Hybrid, and RFC inputs
-
-

Routing Period from YAML input dt

---

src/fortran_routing/Reservoir_Binding/Reservoirs/bind_hybrid.f90
src/python_framework_v02/troute/network/reservoirs/hybrid/hybrid.pyx
src/python_framework_v02/troute/network/reservoirs/test/test_compute_kernel.py

This will now pass the reservoir unit tests. This is the water elevation of an RFC reservoir. The water elevation is now modified from balancing the assimilated RFC values, but I previously did not update the unit test from that change.
-
-
-
1.
-
-

Reservoir-test-quick-value-update

---

src/fortran_routing/diffusive_v02frwk/diffusive.f90
src/python_routing_v02/troute/routing/diffusive_utils.py
src/python_routing_v02/troute/routing/fast_reach/diffusive.pyx

…ty in diffusive.py and added min.value of iniq and +1 to nts_ql_g
In diffusive.f90, added lines for computing initial values of water elevation, celerity, and diffusivity from given values of iniq
In diffusive_utils.py, added minimum values of iniq as 0.0001; added +1 to nts_ql_g
-
-
-
1.
-
-

For diffusive_TU, added computation of initial values of water elevation+celerity+diffusivity; min.value of qlat; nts_ql_g + 1

---

src/python_routing_v02/troute/routing/fast_reach/simple_da.pyx

This pull request proposes a fix to `simple_da` for cold-start DA situations. Specifically, when there is no LastObs file provided and there is a NAN in the first column of the usgs_df, the DA scheme will simply "substitute" the modeled value (i.e. no substitution and a nudge of zero). Addressing #444

DA cold start fix

---

doc/v3_doc.yaml
src/nwm_routing/src/nwm_routing/__main__.py
src/nwm_routing/src/nwm_routing/input.py
src/nwm_routing/src/nwm_routing/log_level_set.py
src/nwm_routing/src/nwm_routing/output.py
src/nwm_routing/src/nwm_routing/preprocess.py
src/python_framework_v02/troute/nhd_network_utilities_v02.py
src/python_routing_v02/troute/routing/compute.py

- the Python logging library is now used in lieu of print statements throughout the codebase. Logging level is set in the configuration file with parameter `log_level`
- A simple check on configuration file content is added and executed with logging level is set to DEBUG. At the moment, the input check simply checks for the existence of required files and directories specified in the YAML file. 
- The logging parameter list has been trimmed - `verbose` and `debuglevel` are no longer needed. 
- The `showtiming` parameter has been repurposed control the construction and printing of an execution time summary report. If `showtiming == True`, then a timing summary is reported along the V3 execution pathway (synchronous only). The timing statements previously reported are still available …

Logging, configuration checks, and timing summary

---

src/nwm_routing/src/nwm_routing/__main__.py
src/nwm_routing/src/nwm_routing/output.py

Allows users to save FVD array to pickle file for quick testing purposes.

flowveldepth to pickle for testing

---

src/python_routing_v02/troute/routing/diffusive_utils.py

Remove accidentally merged debug statement

remove accidentally merged debug statement

---

test/LowerColorado_TX/test_AnA.yaml

mistaken parameter name in yaml file
-
-
-
1.
-
-

fixing parameter name for hybrid routinig

---

src/troute-network/troute/nhd_io.py

yet another adjustment to the variable feature id variable type for the Alaska domain.

Alaska feature id variable fix

---

test/LowerColorado_TX/lower_colorado_refac.yaml

Updating `diffusive_domain` path in `lower_colorado_refac.yaml` Lower Colorado refactor test case.

updating refactor test config input

---

src/troute-network/troute/nhd_io.py
src/troute-nwm/src/nwm_routing/output.py

- Changed handling of FVD dataframe in output.py specifically for producing LAKEOUT files. Previous version was slow because of dataframe format transformations. Those have been omitted for improved speed performance.
- Changed write_waterbody_netcdf function in nhd_io.py to accommodate different format of lakeout dataframe
- 
-
-
1.
-
-

changes to speed up writing lakeout files

---

readme.md
src/troute-nwm/setup.cfg

A couple minor geopandas related clean up edits that escaped #568

update readme and setup.cfg for removing geopandas

---

src/troute-network/troute/AbstractNetwork.py
src/troute-network/troute/DataAssimilation.py
src/troute-network/troute/NHDNetwork.py
src/troute-network/troute/nhd_preprocess.py
src/troute-nwm/src/nwm_routing/__main__.py
src/troute-nwm/src/nwm_routing/preprocess.py

Combining updated NHDNetwork class from PR584 and DA class from PR579, this PR refactored __main__.py in order to make hybrid routing and reservoir/streamflow DA (streamflow DA for MC only for now) fully work with NHDNetwork class.  This work will lead to make t-route become fully compatible with BMI for NHDNetwork. 
-
-
- 
1.  Streamflow results of the hybrid routing for NHDNetwork class with reservoir DA turned off were exactly identical to those of t-route using NWM v3.0 channel network.  Reservoir or Reservoir DA results will be soon to be compared. 
-
-

refactor main.py for making hydbrid routing and reservoir DA fully compatible with NHDNetwork class

---

src/troute-nwm/src/nwm_routing/__main__.py

Fix conditional checking lite_restart parameter to work with new pydantic config module
-
-
- Alter how we check for lite_restart parameters
1.
-
-

update conditional checking for lite_restart

---

test/LowerColorado_TX/test_AnA_V4_NHD.yaml
test/LowerColorado_TX_v4/test_AnA_V4_HYFeature.yaml

Pydantic need to be updated first
-
-
-
1.
-
-

yaml file for V4 HYFeature and NHD

---

src/model_DAforcing.py
src/troute-network/troute/HYFeaturesNetwork.py

Small fixes...
-
- "======" typos in model_DAForcing.py from merging [PR#666](https://github.com/NOAA-OWP/t-route/pull/666)
- Move dropping waterbodies with missing parameters to after bandaid() function call.
1.
-
-

Minor fixes nov2 2023

---

src/troute-network/troute/nhd_io.py

the naming of the columns in the pickle file updated to include the timestamp.
The naming will be like this: q_0_202304020000, v_0_202304020000, d_0_202304020000, ndg_0_202304020000
-
-
-
1.
-
-

updating the column names as timestamp

---

src/troute-network/troute/DataAssimilation.py

only call 'assemble_rfc_dataframes()' if rfc is activated.
- if/else logic to skip calling this function if rfc is not activated. Otherwise an error is thrown.
-
-
1.
-
-

Update logic to call assemble_rfc_dataframes() function

---

src/model_DAforcing.py
src/troute-network/troute/AbstractNetwork.py
src/troute-network/troute/AbstractRouting.py

-Implemented correct coordinate direction for bed depth coordinates in DFlow (basically, water depth is a delta , water level MINUS bed depth, prior it was water level plus bed depth)
-
-
1. Run any example
-
-

Changes for coastal, mainly bed depth coordinate direction

---

src/troute-network/troute/AbstractNetwork.py

minor change on reading DFlow
-
-
-
1.
-
-

update on reading DFlow

---

src/troute-config/troute/config/config.py

- Included file system check for existence of gage directories
-
-
1. Run any example with DA (gages), e.g., Lower Colorado v4 in tests
-
-

Checked for existence of gage directories

---

src/troute-network/troute/HYFeaturesNetwork.py
src/troute-network/troute/rfc_lake_gage_crosswalk.py

Add the Great Lakes as waterbodies. Default method is to use climatological values as their outflows. DA methods are coming...
- Add Great Lakes waterbody IDs to connections dictionary.
- Add Great Lakes to waterbody and waterbody_types dataframes
- Add pre-calculated climatology outflows for each Great Lake.
-
-
1.
-
-

Great lakes routing, network connectivity

---

src/troute-network/troute/HYFeaturesNetwork.py

- Added provision when streamflow DA was turned on, but there were no lakes present - DA parameters are adjusted accordingly
-
-
1.
-
-

Redone old PR 750 - empty lake DF

---

requirements.txt

Update to fix issue 829. This PR specify the correct version of numpy that is compatible with the versions of pyarrow and pandas
-
-
-
1.
-
-

fix to issue 829_
